"use strict";
const FILES=["data-morpheme.js","data-pos.js","data-component.js"],K=["morpheme","pos","component","structure"],C={pink:"#e85d90",purple:"#7557ff",mint:"#20a887",blue:"#4d8df7",yellow:"#efa42f",coral:"#e97857"},LS="malangGrammarLab.v4";
const T=[
["새가 운다.","새가-운다","홑문장","주어와 서술어 관계가 한 번입니다."],["꽃이 아름답다.","꽃이-아름답다","홑문장","주어와 서술어 관계가 한 번입니다."],["민지가 책을 읽는다.","민지가-읽는다","홑문장","목적어가 있어도 주어-서술어 관계는 한 번입니다."],
["비가 오고 바람이 분다.","비가 온다 / 바람이 분다","대등하게 이어진 문장","두 절이 ‘-고’로 나열됩니다."],["나는 갔지만 동생은 남았다.","나는 갔다 / 동생은 남았다","대등하게 이어진 문장","두 절이 ‘-지만’으로 대조됩니다."],["책을 읽거나 음악을 듣는다.","책을 읽는다 / 음악을 듣는다","대등하게 이어진 문장","두 절이 ‘-거나’로 선택 관계를 이룹니다."],
["해가 뜨자 새들이 울었다.","해가 뜬다 / 새들이 울었다","종속적으로 이어진 문장","앞 절이 시간적 배경이 됩니다."],["비가 오면 길이 미끄럽다.","비가 온다 / 길이 미끄럽다","종속적으로 이어진 문장","앞 절이 조건을 나타냅니다."],["날씨가 추워서 강이 얼었다.","날씨가 춥다 / 강이 얼었다","종속적으로 이어진 문장","앞 절이 원인을 나타냅니다."],["공부를 했으므로 시험을 잘 보았다.","공부했다 / 시험을 잘 보았다","종속적으로 이어진 문장","앞 절이 이유나 근거를 나타냅니다."],
["나는 그가 오기를 바란다.","그가 오기","명사절을 안은문장","‘그가 오기’가 목적어 구실을 합니다."],["철수가 범인임이 밝혀졌다.","철수가 범인임","명사절을 안은문장","‘철수가 범인임’이 주어 구실을 합니다."],["우리가 이기기가 쉽지 않다.","우리가 이기기","명사절을 안은문장","‘우리가 이기기’가 주어 구실을 합니다."],
["내가 읽은 책이 재미있다.","내가 읽은","관형절을 안은문장","‘내가 읽은’이 명사 ‘책’을 꾸밉니다."],["비가 오는 날에는 우산을 쓴다.","비가 오는","관형절을 안은문장","‘비가 오는’이 명사 ‘날’을 꾸밉니다."],["내가 산 가방은 가볍다.","내가 산","관형절을 안은문장","‘내가 산’이 명사 ‘가방’을 꾸밉니다."],
["그는 귀가 아프게 소리를 질렀다.","귀가 아프게","부사절을 안은문장","‘귀가 아프게’가 바깥절의 서술어를 꾸밉니다."],["우리는 비가 그치도록 기다렸다.","비가 그치도록","부사절을 안은문장","‘비가 그치도록’이 ‘기다렸다’를 꾸밉니다."],
["철수는 키가 크다.","키가 크다","서술절을 안은문장","‘키가 크다’가 ‘철수는’을 서술합니다."],["코끼리는 코가 길다.","코가 길다","서술절을 안은문장","‘코가 길다’가 ‘코끼리는’을 서술합니다."],
["민지는 “내일 가겠다.”라고 말했다.","“내일 가겠다.”라고","인용절을 안은문장","말을 그대로 직접 인용한 절입니다."],["민지는 내일 가겠다고 말했다.","내일 가겠다고","인용절을 안은문장","말한 내용을 간접 인용한 절입니다."]];
const TYPE=["홑문장","명사절을 안은문장","관형절을 안은문장","부사절을 안은문장","서술절을 안은문장","인용절을 안은문장","대등하게 이어진 문장","종속적으로 이어진 문장"],$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],mix=a=>{a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a},safe=s=>String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;'),choices=e=>mix([e.answer,...mix([...new Set((e.options||[]).filter(x=>x!==e.answer))]).slice(0,3)]);
let D={},key="morpheme",ei=0,order=[],pi=0,answered=0,quiz=[],qi=0,score=0,qans=0,timer,state=read();
function read(){let d={star:0,streak:0,best:0,seen:{morpheme:[],pos:[],component:[],structure:[]},wrong:[],tutorial:0};try{return {...d,...JSON.parse(localStorage.getItem(LS)||"null"),seen:{...d.seen,...JSON.parse(localStorage.getItem(LS)||"null")?.seen}}}catch(e){return d}}
function save(){try{localStorage.setItem(LS,JSON.stringify(state))}catch(e){toast("기기 설정 때문에 기록을 저장하지 못했어요.")}}
function toast(x){let t=$("#toast");t.textContent=x;t.classList.add("is-visible");clearTimeout(timer);timer=setTimeout(()=>t.classList.remove("is-visible"),2200)}
function load(src){return new Promise((ok,no)=>{let s=document.createElement("script");s.src=src;s.onload=ok;s.onerror=no;document.head.append(s)})}
function structure(){let branches=[{icon:"1️⃣",title:"홑문장",desc:"주어-서술어 관계가 한 번입니다.",chips:["새가 운다"]},{icon:"📦",title:"안은문장",desc:"한 절이 다른 문장 안에서 문장 성분 구실을 합니다.",chips:["명사절","관형절","부사절","서술절","인용절"]},{icon:"↔️",title:"대등하게 이어진 문장",desc:"나열·대조·선택의 대등 관계입니다.",chips:["-고","-지만","-거나"]},{icon:"⬇️",title:"종속적으로 이어진 문장",desc:"조건·원인·시간의 종속 관계입니다.",chips:["-면","-어서","-자"]}];return {order:4,icon:"🏗️",nav:"문장 구조",kicker:"STEP 4 · 절의 수와 관계",title:"문장 구조 설계실",subtitle:"주어와 서술어 관계의 수, 안긴절의 기능, 이어진 절의 관계를 분석합니다.",lens:"문장의 길이가 아니라 주어-서술어 관계의 수와 절 사이의 관계를 봅니다.",accent:"#efa42f",soft:"#fff5d9",checklist:["홑문장: 관계가 한 번","겹문장: 관계가 두 번 이상","안은문장: 명사·관형·부사·서술·인용절","이어진문장: 대등/종속"],concepts:{intro:"절의 수와 관계를 차례대로 확인하세요.",root:"문장 구조 = 절의 수 + 절의 관계",branches,note:"‘비가 오면’은 조건 관계로 이어지지만, ‘비가 오는 날’의 ‘비가 오는’은 관형절입니다."},effects:[{title:"절을 이으면 정보가 연결돼요",a:"비가 온다. 바람이 분다.",b:"비가 오고 바람이 분다.",note:"‘-고’가 사건을 나열합니다."},{title:"관형절은 대상을 구체화해요",a:"책이 재미있다.",b:"내가 읽은 책이 재미있다.",note:"어떤 책인지 정보가 더해집니다."}],examples:T.map((x,i)=>{let o=[x[2],...mix(TYPE.filter(a=>a!==x[2])).slice(0,3)];return{id:"s"+(i+1),sentence:x[0],focus:x[1],visual:x[1].split(" / ").map((a,j)=>({text:a,label:j?"절 ②":"분석 단위",note:x[3],tone:["pink","yellow","mint"][j%3]})),question:{prompt:"이 문장의 구조는 무엇인가요?",target:x[1],options:o,answer:x[2],explanation:x[3]},tip:""}})}}
function norm(x){return {...x,concept:x.concepts,effects:x.effects.map(a=>[a.title,a.a,a.b,a.note]),examples:x.examples.map(e=>({id:e.id,sentence:e.sentence,target:e.question.target||e.focus,prompt:e.question.prompt,options:e.question.options,answer:e.question.answer,explanation:e.question.explanation,parts:e.visual,tip:e.tip||""}))}}
async function boot(){try{let l=document.createElement("link");l.rel="stylesheet";l.href="base.css";document.head.insertBefore(l,document.querySelector('link[href="style.css"]'));await Promise.all(FILES.map(load));window.MALANG_STAGES.structure=structure();K.forEach(k=>D[k]=norm(window.MALANG_STAGES[k]));K.forEach(k=>{if(D[k].examples.length<20)throw Error(k+" 예시 부족");D[k].examples.forEach((e,i)=>{if(!e.answer||!Array.isArray(e.options))throw Error(`${k} ${i+1}번 문항 데이터 오류`);if(!e.options.includes(e.answer))e.options=[e.answer,...e.options]})});bind();$(".brand small").textContent="2022 개정 화법과 언어 연계";$(".standard-code").textContent="언어 탐구·활용";stats();review();view("home");if(!state.tutorial)setTimeout(tutorial,400)}catch(e){console.error(e);document.body.innerHTML=`<main><h1>앱을 불러오지 못했습니다.</h1><p>${e.message}</p></main>`}}
function tutorial(){let d=$("#tutorialDialog");d?.showModal?d.showModal():alert("개념→예시→분류→효과→복습 순서로 학습하세요.");state.tutorial=1;save()}
function view(v){$$('.view').forEach(x=>x.classList.toggle('is-visible',x.dataset.viewPanel===v));$$('.stage-tab').forEach(x=>x.classList.toggle('is-active',v==='stage'?x.dataset.stage===key:x.dataset.view===v));if(v==='review')review();if(v==='quiz'){$("#quizStartPanel").classList.remove("is-hidden");$("#quizPlayPanel").classList.add("is-hidden");$("#quizResultPanel").classList.add("is-hidden")}scrollTo({top:0,behavior:"smooth"})}
function stats(){$("#starCount").textContent=state.star;$("#streakCount").textContent=state.streak;$("#bestScore").textContent=state.best;$("#pathGrid").innerHTML=K.map(k=>{let d=D[k],n=Math.min(20,state.seen[k].length);return `<article class="path-card" data-open="${k}" tabindex="0" style="--card-soft:${d.soft}"><span class="card-icon">${d.icon}</span><h3>${d.order}. ${d.nav}</h3><p>${d.subtitle}</p><div class="path-progress"><div class="path-progress-top"><span>예시 ${n}/20</span><strong>${n*5}%</strong></div><div class="progress-track"><span style="width:${n*5}%;background:${d.accent}"></span></div></div></article>`}).join("");$("#overallProgressText").textContent=`${K.filter(k=>state.seen[k].length>=20).length} / 4단계 완료`}
function openStage(k,m="concept",id){key=k;let d=D[k],n=id?d.examples.findIndex(x=>x.id===id):0;ei=n<0?0:n;order=mix(d.examples.map((_,i)=>i));pi=0;document.documentElement.style.setProperty("--stage-accent",d.accent);document.documentElement.style.setProperty("--stage-soft",d.soft);$("#stageKicker").textContent=d.kicker;$("#stageTitle").textContent=d.title;$("#stageSubtitle").textContent=d.subtitle;$("#stageIcon").textContent=d.icon;$("#stageLens").textContent=d.lens;$("#stageChecklist").innerHTML=d.checklist.map(x=>`<div class="stage-check"><span>✓</span>${x}</div>`).join("");$("#conceptCountBadge").textContent=`예시 ${d.examples.length}개`;concept();effects();example();practice();stageReview();mode(m);view("stage")}
function mode(m){$$('.micro-step').forEach(x=>x.classList.toggle('is-active',x.dataset.mode===m));$$('.mode-panel').forEach(x=>x.classList.toggle('is-visible',x.dataset.modePanel===m));if(m==="example")example();if(m==="practice")practice();if(m==="review")stageReview()}
function concept(){let c=D[key].concept;$("#conceptMap").innerHTML=`<p class="concept-intro">${c.intro}</p><div class="concept-tree"><div class="concept-root">${c.root}</div><div class="concept-branches">${c.branches.map(b=>`<article class="concept-branch"><h3><span>${b.icon}</span>${b.title}</h3><p>${b.desc}</p><div class="concept-chip-wrap">${b.chips.map(x=>`<span class="concept-chip">${x}</span>`).join("")}</div></article>`).join("")}</div><div class="concept-note">💡 ${c.note}</div></div>`}
function mark(e){if(!state.seen[key].includes(e.id)){state.seen[key].push(e.id);save();stats()}let n=Math.min(20,state.seen[key].length);$("#stageSeenCount").textContent=`${n} / 20`;$("#stageProgressBar").style.width=n*5+"%"}
function example(){let d=D[key];ei=(ei+d.examples.length)%d.examples.length;let e=d.examples[ei];mark(e);$("#examplePosition").textContent=`${ei+1} / ${d.examples.length}`;$("#examplePrompt").innerHTML=`<strong>${e.sentence}</strong> · 조각을 눌러 근거를 확인하세요.`;$("#exampleSelect").innerHTML=d.examples.map((x,i)=>`<option value="${i}" ${i===ei?"selected":""}>${i+1}. ${x.sentence}</option>`).join("");$("#sentenceDisplay").innerHTML=e.parts.map((x,i)=>`<button class="token-button" data-token="${i}" style="--token-color:${C[x.tone]||C.purple}"><span class="token-text">${x.text}</span><span class="token-label">${x.label}</span></button>`).join("");$("#tokenLegend").innerHTML="";$("#analysisFeedback").innerHTML="<span>👆</span><p>조각을 누르면 분석 근거가 나타납니다.</p>"}
function practice(){let e=D[key].examples[order[pi]];answered=0;$("#practiceProgress").textContent=`${pi+1} / ${order.length}`;$("#practiceTag").textContent=D[key].nav;$("#practiceQuestion").textContent=e.prompt;$("#practiceTarget").textContent=`${e.sentence} → ${e.target}`;$("#practiceOptions").innerHTML=choices(e).map(x=>`<button class="option-button" data-answer="${safe(x)}">${x}</button>`).join("");$("#practiceFeedback").className="answer-feedback";$("#nextPracticeButton").classList.add("is-hidden")}
function check(a,q=0){let e=q?quiz[qi].e:D[key].examples[order[pi]],k=q?quiz[qi].k:key;if(q?qans:answered)return;q?qans=1:answered=1;let ok=a===e.answer;$$(`[data-${q?"qanswer":"answer"}]`).forEach(b=>{b.disabled=1;if(b.dataset[q?"qanswer":"answer"]===e.answer)b.classList.add("is-correct");if(b.dataset[q?"qanswer":"answer"]===a&&!ok)b.classList.add("is-wrong")});let f=$(q?"#quizFeedback":"#practiceFeedback");f.className=`answer-feedback is-visible ${ok?"correct":"wrong"}`;f.innerHTML=`<strong>${ok?"정답!":"정답은 ‘"+e.answer+"’"}</strong> ${e.explanation}`;if(ok){state.star++;state.streak++;if(q)score++}else{state.streak=0;let r=state.wrong.find(x=>x.k===k&&x.id===e.id);r?r.n++:state.wrong.push({k,id:e.id,n:1})}if(!state.seen[k].includes(e.id))state.seen[k].push(e.id);save();stats();$(q?"#nextQuizButton":"#nextPracticeButton").classList.remove("is-hidden")}
function effects(){$("#effectDeck").innerHTML=D[key].effects.map(x=>`<article class="effect-card"><h3>${x[0]}</h3><div class="effect-compare"><div class="effect-sentence">${x[1]}</div><div class="effect-arrow">→</div><div class="effect-sentence">${x[2]}</div></div><p class="effect-note">${x[3]}</p></article>`).join("")}
function stageReview(){let r=state.wrong.filter(x=>x.k===key),c=$("#stageReviewContent");c.innerHTML=r.length?`<div class="review-cards">${r.map(x=>{let e=D[key].examples.find(a=>a.id===x.id);return `<article class="focus-card"><h3>${e.answer}</h3><p>${e.explanation}</p><button class="secondary-button" data-re="${e.id}">분석 보기</button></article>`}).join("")}</div>`:'<div class="review-empty"><div><span>🌱</span><h3>이 단계의 오답이 없어요.</h3><p>새 예시를 탐색하거나 종합 게임에 도전하세요.</p></div></div>'}
function startQuiz(){quiz=mix(K.flatMap(k=>mix(D[k].examples).slice(0,3).map(e=>({k,e}))));qi=score=0;$("#quizStartPanel").classList.add("is-hidden");$("#quizPlayPanel").classList.remove("is-hidden");quizQ()}
function quizQ(){if(qi>=12){state.best=Math.max(state.best,score);save();stats();$("#quizPlayPanel").classList.add("is-hidden");let r=$("#quizResultPanel");r.classList.remove("is-hidden");r.innerHTML=`<div class="result-score">${score}<small>/12</small></div><h2>${score>=9?"핵심 기준이 잘 잡혔어요.":"오답 집중 복습으로 연결해 보세요."}</h2><button class="primary-button" data-restart>다시 도전</button>`;return}let {k,e}=quiz[qi];qans=0;$("#quizNumber").textContent=`${qi+1} / 12`;$("#quizProgressBar").style.width=qi/12*100+"%";$("#quizLiveScore").textContent=score+"점";$("#quizTag").textContent=`${D[k].icon} ${D[k].nav}`;$("#quizQuestion").textContent=e.prompt;$("#quizTarget").textContent=`${e.sentence} → ${e.target}`;$("#quizOptions").innerHTML=choices(e).map(x=>`<button class="option-button" data-qanswer="${safe(x)}">${x}</button>`).join("");$("#quizFeedback").className="answer-feedback";$("#nextQuizButton").classList.add("is-hidden")}
function review(){let r=state.wrong,d=$("#reviewDashboard");d.innerHTML=r.length?`<div class="review-cards">${r.map(x=>{let e=D[x.k]?.examples.find(a=>a.id===x.id);return e?`<article class="focus-card"><h3>${D[x.k].icon} ${e.answer}</h3><p><strong>${e.sentence}</strong><br>${e.explanation}</p><button class="secondary-button" data-global="${x.k}|${x.id}">다시 보기</button></article>`:""}).join("")}</div>`:'<div class="review-empty"><div><span>🎉</span><h3>저장된 오답이 없어요.</h3><p>틀린 개념은 같은 영역의 새 문장으로 다시 확인할 수 있습니다.</p></div></div>'}
function bind(){document.addEventListener("click",e=>{let x=e.target.closest("[data-view]");if(x)return view(x.dataset.view);x=e.target.closest("[data-stage]");if(x)return openStage(x.dataset.stage);x=e.target.closest("[data-open]");if(x)return openStage(x.dataset.open);x=e.target.closest("[data-mode]");if(x)return mode(x.dataset.mode);x=e.target.closest("[data-token]");if(x){let a=D[key].examples[ei].parts[+x.dataset.token];$("#analysisFeedback").innerHTML=`<span>🔎</span><p><strong>${a.text} → ${a.label}</strong><br>${a.note}</p>`;return}x=e.target.closest("[data-answer]");if(x)return check(x.dataset.answer);x=e.target.closest("[data-qanswer]");if(x)return check(x.dataset.qanswer,1);x=e.target.closest("[data-re]");if(x){ei=D[key].examples.findIndex(a=>a.id===x.dataset.re);return mode("example")}x=e.target.closest("[data-global]");if(x){let [k,id]=x.dataset.global.split("|");return openStage(k,"example",id)}if(e.target.closest("[data-restart]"))return startQuiz()});$("#startLearningButton").onclick=()=>openStage("morpheme");$("#tutorialButton").onclick=$("#openTutorialButton").onclick=tutorial;$("#randomExampleButton").onclick=()=>{ei=Math.floor(Math.random()*D[key].examples.length);mode("example")};$("#prevExampleButton").onclick=()=>{ei--;example()};$("#nextExampleButton").onclick=()=>{ei++;example()};$("#exampleSelect").onchange=e=>{ei=+e.target.value;example()};$("#nextPracticeButton").onclick=()=>{pi=(pi+1)%order.length;practice()};$("#startQuizButton").onclick=startQuiz;$("#nextQuizButton").onclick=()=>{qi++;quizQ()};$("#clearWrongButton").onclick=()=>{state.wrong=[];save();review()};$("#resetButton").onclick=()=>{if(confirm("모든 학습 기록을 초기화할까요?")){localStorage.removeItem(LS);location.reload()}}}
window.addEventListener("DOMContentLoaded",boot);
